# Время ожидания до ввода следущего ввода команды afk, после ее использования
WaitForAFK: 75
teleport:
  # Включен ли имунитет к телепортам
  allowImmunity: false
  # Запрещает телепортироваться внутрь блоков с помощью жемчуга эндера
  disallowPearlTeleportIntoBlock: true
speedDefault:
  # Стандартная скорость пешком
  walk: 0.2
  # Стандартная скорость полета
  fly: 0.2
Afk:
  # Время неактивности игрока, через которое ему будет назначен статус AFK
  Auto: 0
  # Получить время простоя в афк, после которого сервер выкинет игрока
  AutoKick: 0
  # Помещать ли в специальную команду игроков, которые на ходятся в афк
  Team: false
Combat:
  # Включен ли режим убийства игроков, которые выходят во время боя
  KillCombatLeavers: false
  # Включены ли сообщения у режима защиты пвп
  CombatMessages: false
  # Длительность боя, после которой режим защиты пвп выключается
  CombatTime: 5
Timedstop:
  # Включино ли автоматическое отключение сервера
  Enable: false
  # Абсолютно ли время выключение сервера или относительное
  FixedTime: true
  # Получить фиксированное время выключение сервера
  Time: 04:00:00:000
  # Получить относительное время выключения сервера (в часах)
  Delyhour: 1
  # Предупреждения перед автоматическим выключением сервера
  Warnings: []
# Система защиты от dos-атак
antidos:
  enabled: true