teleport:
  # Включен ли имунитет к телепортам
  allowImmunity: false
  # Запрещает телепортироваться внутрь блоков с помощью жемчуга эндера
  disallowPearlTeleportIntoBlock: true
speedDefault:
  # Стандартная скорость пешком
  walk: 0.2
  # Стандартная скорость полета
  fly: 0.2
Combat:
  # Включен ли режим убийства игроков, которые выходят во время боя
  KillCombatLeavers: false
  # Включены ли сообщения у режима защиты пвп
  CombatMessages: false
  # Длительность боя, после которой режим защиты пвп выключается
  CombatTime: 5
Timedstop:
  # Включено ли автоматическое отключение сервера
  Enable: false
  # Абсолютно ли время выключение сервера или относительное
  FixedTime: true
  # Получить фиксированное время выключение сервера
  Time: 04:00:00:000
  # Получить относительное время выключения сервера (в часах)
  Delyhour: 1
  # Предупреждения перед автоматическим выключением сервера
  Warnings: []
# Система защиты от dos-атак
antidos:
  enabled: true
  # Запретить вход, если в нике указанный префикс
  # Если null - то выключено
  disallowedNamePrefix: null