name: SCEssentials
version: 6.2
api-version: 1.16
main: ru.seriouscompany.essentials.SCCore
author: Vadimka
commands:
  afk:
    description: Афк
    usage: /<command>
  pinfo:
    description: Информаци о игроке
    usage: /<command> <Игрок>
  fly:
    description: Включить полет
    usage: /<command> [Игрок]
  scereload:
    description: Перезагрузка плагина
    usage: /<command>
  heal:
    description: Установить здоровье
    usage: /<command> <Количество/Игрок> [кол здоровья]
  feed:
    description: Накормить игрока
    usage: /<command> [Игрок]
  oi:
    description: Открыть инвентарь игрока
    usage: /<command> <Игрок>
  oe:
    description: Открыть эндер сундук игрока
    usage: /<command> <Игрок>
  sleepignore:
    description: Игнорировать сон
    usage: /<command>
  tpw:
    description: Переместиться в спаун указанного мира
    usage: /<command> <Мир> [Игрок]
  suicide:
    description: Самоуничтожиться
    usage: /<command>
  world:
    description: Команда миров
    usage: /<command> <Команда>
  lockbook:
    description: Открыть книгу для записи
    user: /<command>
  freeze:
    description: Заморозить или разморозить игрока
    user: /<command> <Игрок>
  accept:
    description: Принять запрос
    user: /<command>
  specmode:
    description: Режим зрителя
    user: /<command>
  tpp:
    description: Телепортироваться к игроку
    user: /<command> <Игрок>
  tpb:
    description: Телепортироваться к кровати игрока
    user: /<command> <Игрок>
  undress:
    description: Раздеть игрока
    user: /<command> <Игрок>
  passive:
    description: Пассивный режим
    user: /<command>
  bunder:
    description: Стави т блок под вами
    user: /<command>
permissions:
  scessentials.*:
    description: Все преимущества плагина
    default: op
    children:
      scessentials.afk: true
      scessentials.feed: true
      scessentials.fly.*: true
      scessentials.heal.*: true
      scessentials.openender: true
      scessentials.openinventory: true
      scessentials.pinfo: true
      scessentials.reload: true
      scessentials.sleepignore: true
      scessentials.teleportworld: true
      scessentials.suicide: true
      scessentials.freeze: true
      scessentials.spectator: true
      scessentials.world.*: true
      scessentials.teleport.*: true
      scessentials.undress: true
      scessentials.passivemode: true
      scessentials.blockunderme: true
  scessentials.suicide:
    description: Дает преимущества суицида
    default: true
  scessentials.afk:
    description: Дает возможность отлучиться от компьютера
    default: true
  scessentials.combat:
    description: Дает возможность выходить из игры во время боя
    default: false
  scessentials.feed:
    description: Дает преимущество восстановить голод
    default: false
  scessentials.fly.*:
    description: Дает преимущество включить полет себе и другим
    default: false
    children:
      scessentials.fly: true
      scessentials.fly.other: true
  scessentials.fly:
    description: Дает преимущество включить полет
    default: false
  scessentials.fly.other:
    description: Дает преимущество включить полет другим
    default: false
  scessentials.heal.*:
    description: Дает преимущество вылечить себя и других
    default: false
    children:
      scessentials.heal: true
      scessentials.heal.other: true
  scessentials.heal:
    description: Дает преимущество вылечить себя
    default: false
  scessentials.heal.other:
    description: Дает преимущество вылечить других
    default: false
  scessentials.openender:
    description: Дает преимущество открыть эндер-сундук
    default: false
  scessentials.openinventory:
    description: Дает преимущество открыть инвентарь игроков
    default: false
  scessentials.undress:
    description: Дает право раздевать игроков
    default: false
  scessentials.pinfo:
    description: Показывает информацию об игроке
    default: false
  scessentials.reload:
    description: Перезагружает конфигурацию плагина
    default: false
  scessentials.sleepignore:
    description: Дает преимущество игнорировать сон
    default: false
  scessentials.freeze:
    description: Возможность заморозить игрока
    default: false
  scessentials.spectator:
    description: Возможность включить режим зрителя
    default: false
  scessentials.teleport.*:
    description: Возможность телепортироваться
    default: false
    children:
      scessentials.teleport.toplayers: true
      scessentials.teleport.tobed: true
      scessentials.teleport.tobed.other: true
  scessentials.teleport.toplayers:
    description: Возможность телепортироваться к игрокам
    default: false
  scessentials.teleport.tobed:
    description: Телепортироваться на свою кровать
    default: false
  scessentials.teleport.tobed.other:
    description: Телепортироваться на чужую кровать
    default: false
  scessentials.teleport.immunity:
    description: Имунитет к телепортам к себе
    default: false
  scessentials.world.*:
    description: Дает преимущество работать с командами миров
    default: false
    children:
      scessentials.world.teleport: true
      scessentials.world.list: true
      scessentials.world.unload: true
      scessentials.world.load: true
  scessentials.world.teleport:
    description: Дает преимущество телепортироваться между мирами
    default: false
  scessentials.world.list:
    description: Дает преимущество смотреть список миров
    default: false
  scessentials.world.unload:
    description: Возможность отгружать миры
    default: false
  scessentials.world.load:
    description: Возможность подгружать миры
    default: false
  scessentials.passivemode:
    description: Возможность использовать пассивный режим
    default: false
  scessentials.blockunderme:
    description: Возможность поставить блок под собой
    default: false

